### PR TITLE
Create simplecalc.py

### PR DESCRIPTION
**Pull request by aniruddhaadak80**
For issue : #11

### CODE REVIEW

**Comment by Badger0909** [comment]
hello @aniruddhaadak80,
Your arithmetic calculator and BMI calculator seem to be working fine, however the graphing calculator does not work, most likely a support or incompatibility issue with matplotlib. If you can find a solution, great, otherwise your BMI and arithmetic calculator can be enough for a pull request. Once you change it I will merge.

**Comment by hriteshMaikap** [comment]
Hey! I guess @aniruddhaadak80 has already worked on the issue, a request is if he is done with arithmetic and BMI calculator, can I make the Graphing Calculator?

**Comment by Badger0909** [comment]
that works, please make a seperate pull request

**Comment by aniruddhaadak80** [comment]
Okey , I am working on this .

**Comment by aniruddhaadak80** [comment]
Check it please . I have updated this .

**Pull request merged**
